required = [
  "github.com/alecthomas/gometalinter",
  "github.com/vektra/mockery/cmd",
  "github.com/cweill/gotests/gotests",
  "github.com/swaggo/swag/cmd/swag",
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.4.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.9.1"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.15.5"

[[constraint]]
  name = "go.mongodb.org/mongo-driver"
  version = "1.1.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.3"

[[constraint]]
  name = "github.com/caarlos0/env"
  version = "6.1.0"

[[constraint]]
  name = "github.com/swaggo/swag"
  version = "1.6.3"

[[constraint]]
  name = "github.com/alecthomas/template"
  revision = "fb15b899a75114aa79cc930e33c46b577cc664b1"

[[constraint]]
  name = "go.etcd.io/etcd"
  version = "3.4.3"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.4.2"

[[constraint]]
  name = "github.com/go-log/log"
  version = "0.2.0"

[[constraint]]
  name = "github.com/thewizardplusplus/go-http-utils"
  version = "1.1.0"
