required = [
  "github.com/alecthomas/gometalinter",
  "github.com/vektra/mockery/cmd/mockery",
  "github.com/cweill/gotests/gotests",
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.4.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.1.1"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.15.5"

[[constraint]]
  name = "go.mongodb.org/mongo-driver"
  version = "1.1.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.3"

[[constraint]]
  name = "github.com/caarlos0/env"
  version = "6.1.0"

[[constraint]]
  name = "github.com/swaggo/swag"
  version = "1.6.3"

[[constraint]]
  branch = "master"
  name = "github.com/alecthomas/template"

[[constraint]]
  name = "go.etcd.io/etcd"
  version = "3.4.3"
